package coordination.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.AttributeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.IAttributeDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.generator.template.IfMacroContext;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodeContext;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public final boolean NEEDS_OPCONTEXT = false;

  public static Object propertyMacro_GetPropertyValue_4593348108327491427(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(_context.getNode(), "initialstate", false), "virtual_getStateName_6168113672289375101", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_2985869118320062810(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name").replaceAll("[^-._:a-zA-Z0-9]", "");
  }

  public static Object propertyMacro_GetPropertyValue_2985869118319551975(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name").replaceAll("[^-_.a-zA-Z0-9]", "");
  }

  public static Object propertyMacro_GetPropertyValue_4593348108329821999(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(AttributeOperations.getAttribute(_context.getNode(), new IAttributeDescriptor.NodeAttribute("coordination.structure.Comment")), "comment");
  }

  public static Object propertyMacro_GetPropertyValue_4593348108329876792(final PropertyMacroContext _context) {
    return "'" + "Entering state " + SPropertyOperations.getString(_context.getNode(), "name") + "'";
  }

  public static Object propertyMacro_GetPropertyValue_4593348108330332728(final PropertyMacroContext _context) {
    return "'" + BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(SNodeOperations.cast(_context.getNode(), "coordination.structure.Transition"), "condition", true), "virtual_getEventName_4593348108330088614", new Object[]{}) + "'";
  }

  public static Object propertyMacro_GetPropertyValue_4593348108330351830(final PropertyMacroContext _context) {
    return "'" + SPropertyOperations.getInteger(SNodeOperations.cast(SLinkOperations.getTarget(SNodeOperations.cast(_context.getNode(), "coordination.structure.Transition"), "condition", true), "coordination.structure.WaitDuration"), "milliseconds") + "ms" + "'";
  }

  public static Object propertyMacro_GetPropertyValue_4593348108329918526(final PropertyMacroContext _context) {
    return "'" + "Leaving state " + SPropertyOperations.getString(_context.getNode(), "name") + "'";
  }

  public static Object propertyMacro_GetPropertyValue_4593348108327725502(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_getStateName_6168113672289375101", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_4593348108329816589(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(AttributeOperations.getAttribute(_context.getNode(), new IAttributeDescriptor.NodeAttribute("coordination.structure.Comment")), "comment");
  }

  public static Object propertyMacro_GetPropertyValue_4593348108329999129(final PropertyMacroContext _context) {
    return "'" + "Entering composite state " + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_getStateName_6168113672289375101", new Object[]{}) + "'";
  }

  public static Object propertyMacro_GetPropertyValue_4593348108330048459(final PropertyMacroContext _context) {
    return "'" + "Leaving composite state " + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_getStateName_6168113672289375101", new Object[]{}) + "'";
  }

  public static Object propertyMacro_GetPropertyValue_4593348108327738693(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_getStateName_6168113672289375101", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_4593348108329807019(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(AttributeOperations.getAttribute(_context.getNode(), new IAttributeDescriptor.NodeAttribute("coordination.structure.Comment")), "comment");
  }

  public static Object propertyMacro_GetPropertyValue_4593348108329978288(final PropertyMacroContext _context) {
    return "entering" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_getStateName_6168113672289375101", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_4593348108329978300(final PropertyMacroContext _context) {
    return "'" + "Entering parallel state " + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_getStateName_6168113672289375101", new Object[]{}) + "'";
  }

  public static Object propertyMacro_GetPropertyValue_4593348108327739547(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_getStateName_6168113672289375101", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_4593348108330026057(final PropertyMacroContext _context) {
    return "leaving" + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_getStateName_6168113672289375101", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_4593348108330026069(final PropertyMacroContext _context) {
    return "'" + "Leaving parallel state " + BehaviorReflection.invokeVirtual(String.class, _context.getNode(), "virtual_getStateName_6168113672289375101", new Object[]{}) + "'";
  }

  public static Object propertyMacro_GetPropertyValue_4593348108330080016(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(_context.getNode(), "condition", true), "virtual_getEventName_4593348108330088614", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_4593348108330075970(final PropertyMacroContext _context) {
    return BehaviorReflection.invokeVirtual(String.class, SLinkOperations.getTarget(_context.getNode(), "target", false), "virtual_getStateName_6168113672289375101", new Object[]{});
  }

  public static Object propertyMacro_GetPropertyValue_4593348108329006492(final PropertyMacroContext _context) {
    return "'" + SPropertyOperations.getString(_context.getNode(), "message") + "'";
  }

  public static Object propertyMacro_GetPropertyValue_4593348108329007289(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "eventname");
  }

  public static Object propertyMacro_GetPropertyValue_3177877371210534456(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "name");
  }

  public static Object propertyMacro_GetPropertyValue_3177877371210547604(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "src");
  }

  public static Object propertyMacro_GetPropertyValue_3177877371210550454(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), "expr");
  }

  public static boolean ifMacro_Condition_3177877371210054015(final IfMacroContext _context) {
    return ListSequence.fromList(SLinkOperations.getTargets(_context.getNode(), "data", true)).isNotEmpty();
  }

  public static boolean ifMacro_Condition_4593348108329829335(final IfMacroContext _context) {
    return (AttributeOperations.getAttribute(_context.getNode(), new IAttributeDescriptor.NodeAttribute("coordination.structure.Comment")) != null);
  }

  public static boolean ifMacro_Condition_4593348108330283837(final IfMacroContext _context) {
    return SNodeOperations.isInstanceOf(SLinkOperations.getTarget(SNodeOperations.cast(_context.getNode(), "coordination.structure.Transition"), "condition", true), "coordination.structure.WaitDuration");
  }

  public static boolean ifMacro_Condition_4593348108329845125(final IfMacroContext _context) {
    return (AttributeOperations.getAttribute(_context.getNode(), new IAttributeDescriptor.NodeAttribute("coordination.structure.Comment")) != null);
  }

  public static boolean ifMacro_Condition_4593348108329839782(final IfMacroContext _context) {
    return (AttributeOperations.getAttribute(_context.getNode(), new IAttributeDescriptor.NodeAttribute("coordination.structure.Comment")) != null);
  }

  public static boolean ifMacro_Condition_3177877371210541021(final IfMacroContext _context) {
    return isNotEmptyString(SPropertyOperations.getString(_context.getNode(), "src"));
  }

  public static boolean ifMacro_Condition_3177877371210550461(final IfMacroContext _context) {
    return isNotEmptyString(SPropertyOperations.getString(_context.getNode(), "expr"));
  }

  public static SNode sourceNodeQuery_1677798668035515345(final SourceSubstituteMacroNodeContext _context) {
    return SLinkOperations.getTarget(_context.getNode(), "condition", true);
  }

  public static Iterable<SNode> sourceNodesQuery_3177877371210127190(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "data", true);
  }

  public static Iterable<SNode> sourceNodesQuery_4593348108327724366(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "states", true);
  }

  public static Iterable<SNode> sourceNodesQuery_4593348108327773018(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "onentry", true);
  }

  public static Iterable<SNode> sourceNodesQuery_4593348108330310047(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "transitions", true);
  }

  public static Iterable<SNode> sourceNodesQuery_4593348108329021041(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "onexit", true);
  }

  public static Iterable<SNode> sourceNodesQuery_4593348108329050140(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "transitions", true);
  }

  public static Iterable<SNode> sourceNodesQuery_4593348108329095111(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "onentry", true);
  }

  public static Iterable<SNode> sourceNodesQuery_4593348108329101547(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "onexit", true);
  }

  public static Iterable<SNode> sourceNodesQuery_4593348108329109241(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "transitions", true);
  }

  public static Iterable<SNode> sourceNodesQuery_4593348108329061596(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "states", true);
  }

  public static Iterable<SNode> sourceNodesQuery_4593348108329119700(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "onentry", true);
  }

  public static Iterable<SNode> sourceNodesQuery_4593348108329136348(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "onexit", true);
  }

  public static Iterable<SNode> sourceNodesQuery_4593348108329141964(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "transitions", true);
  }

  public static Iterable<SNode> sourceNodesQuery_4593348108329164018(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "states", true);
  }

  public static Iterable<SNode> sourceNodesQuery_3177877371210571075(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getTargets(_context.getNode(), "content", true);
  }

  private static boolean isNotEmptyString(String str) {
    return str != null && str.length() > 0;
  }
}
