package coordination.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.NodeAttribute_BehaviorDescriptor;

public class Comment_BehaviorDescriptor extends NodeAttribute_BehaviorDescriptor {
  public Comment_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coordination.structure.Comment";
  }
}
