package coordination.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.core.behavior.INamedConcept_Behavior;

public class CompositeState_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements StateLike_BehaviorDescriptor, StateContainer_BehaviorDescriptor {
  public CompositeState_BehaviorDescriptor() {
  }

  public String virtual_getEntryMessage_6168113672289374367(SNode thisNode) {
    return CompositeState_Behavior.virtual_getEntryMessage_6168113672289374367(thisNode);
  }

  public String virtual_getExitMessage_6168113672289374913(SNode thisNode) {
    return CompositeState_Behavior.virtual_getExitMessage_6168113672289374913(thisNode);
  }

  public String virtual_getFqName_1213877404258(SNode thisNode) {
    return INamedConcept_Behavior.virtual_getFqName_1213877404258(thisNode);
  }

  public String virtual_getStateName_6168113672289375101(SNode thisNode) {
    return CompositeState_Behavior.virtual_getStateName_6168113672289375101(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "coordination.structure.CompositeState";
  }
}
