package coordination.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;

public interface Condition_BehaviorDescriptor {
  public String virtual_getEventName_4593348108330088614(SNode thisNode);
}
