package coordination.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class FireEvent_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements Action_BehaviorDescriptor {
  public FireEvent_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coordination.structure.FireEvent";
  }
}
