package coordination.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class JEXLCondition_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements Condition_BehaviorDescriptor {
  public JEXLCondition_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coordination.structure.JEXLCondition";
  }
}
