package coordination.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class JEXLCondition_Behavior {
  public static void init(SNode thisNode) {
    SPropertyOperations.set(thisNode, "jexlExpression", "");
  }
}
