package coordination.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class LogMessage_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements Action_BehaviorDescriptor {
  public LogMessage_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coordination.structure.LogMessage";
  }
}
