package coordination.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.NodeAttribute_BehaviorDescriptor;

public class MultiLineComment_BehaviorDescriptor extends NodeAttribute_BehaviorDescriptor {
  public MultiLineComment_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coordination.structure.MultiLineComment";
  }
}
