package coordination.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;

public interface StateContainer_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor, ICanBeCommented_BehaviorDescriptor {
}
