package coordination.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.INamedConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public interface StateLike_BehaviorDescriptor extends INamedConcept_BehaviorDescriptor, ICanBeCommented_BehaviorDescriptor {
  public String virtual_getEntryMessage_6168113672289374367(SNode thisNode);
  public String virtual_getExitMessage_6168113672289374913(SNode thisNode);
  public String virtual_getStateName_6168113672289375101(SNode thisNode);
}
