package coordination.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class String_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public String_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coordination.structure.String";
  }
}
