package coordination.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;
import org.jetbrains.mps.openapi.model.SNode;

public class WaitDuration_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements Condition_BehaviorDescriptor {
  public WaitDuration_BehaviorDescriptor() {
  }

  public String virtual_getEventName_4593348108330088614(SNode thisNode) {
    return WaitDuration_Behavior.virtual_getEventName_4593348108330088614(thisNode);
  }

  @Override
  public String getConceptFqName() {
    return "coordination.structure.WaitDuration";
  }
}
