package coordination.behavior;

/*Generated by MPS */

import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.smodel.behaviour.BehaviorReflection;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;

public class WaitDuration_Behavior {
  public static void init(SNode thisNode) {
  }

  public static String virtual_getEventName_4593348108330088614(SNode thisNode) {
    return BehaviorReflection.invokeVirtual(String.class, SNodeOperations.cast(SNodeOperations.getParent(SNodeOperations.getParent(thisNode)), "coordination.structure.StateLike"), "virtual_getStateName_6168113672289375101", new Object[]{}) + "wait" + SPropertyOperations.getInteger(thisNode, "milliseconds") + "ms";
  }
}
